name: juice-contracts-system-tests
on:
  pull_request:
    branches:
      - main
      - foundry
  push:
    branches:
      - main
      - foundry
jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run tests
        run: forge test 
